# Generated by Django 3.2.9 on 2021-11-23 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inscricao',
            new_name='Cadastro',
        ),
    ]
