# Generated by Django 3.2.9 on 2021-11-23 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0003_auto_20211123_2003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CadastroAluno',
            new_name='CadastroAlunos',
        ),
    ]
