# Generated by Django 3.2.9 on 2021-11-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0004_rename_cadastroaluno_cadastroalunos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=155)),
                ('cpf', models.IntegerField()),
                ('idade', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=155)),
                ('telefone', models.IntegerField()),
                ('aulas', models.CharField(max_length=155)),
            ],
        ),
        migrations.AlterField(
            model_name='cadastroalunos',
            name='cpf',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cadastroalunos',
            name='telefone',
            field=models.IntegerField(),
        ),
    ]
