# Generated by Django 3.2.9 on 2021-11-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0005_auto_20211125_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aula', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='CadastroCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DecimalField(decimal_places=2, max_digits=11)),
                ('saida', models.DecimalField(decimal_places=2, max_digits=11)),
                ('data', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CadastroProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=155)),
                ('cpf', models.IntegerField()),
                ('email', models.EmailField(max_length=155)),
                ('telefone', models.IntegerField()),
                ('aula', models.CharField(max_length=155)),
            ],
        ),
        migrations.DeleteModel(
            name='CadastroProfessor',
        ),
    ]
