# Generated by Django 3.2.9 on 2021-11-25 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0007_alter_cadastrocaixa_saida'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CadastroCaixa',
        ),
    ]
