# Generated by Django 3.2.9 on 2021-11-26 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0008_delete_cadastrocaixa'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroTerapia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terapia', models.CharField(max_length=155)),
            ],
        ),
        migrations.DeleteModel(
            name='CadastroAula',
        ),
        migrations.RenameField(
            model_name='cadastroprofissional',
            old_name='aula',
            new_name='terapia',
        ),
    ]
