# Generated by Django 3.2.9 on 2021-11-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0009_auto_20211125_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastroterapia',
            name='descricao',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='cadastroterapia',
            name='terapia',
            field=models.CharField(default='', max_length=155),
        ),
    ]
