# Generated by Django 3.2.9 on 2021-11-26 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0009_auto_20211125_2104'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CadastroAlunos',
            new_name='CadastroAluno',
        ),
    ]
