# Generated by Django 3.2.9 on 2021-11-27 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0010_rename_cadastroalunos_cadastroaluno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CadastroTerapia',
        ),
    ]
