# Generated by Django 3.2.9 on 2021-11-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0010_auto_20211128_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroterapia',
            name='descricao',
            field=models.CharField(default='', max_length=155),
        ),
    ]
