# Generated by Django 3.2.9 on 2021-11-29 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0011_alter_cadastroterapia_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastroterapia',
            old_name='descricao',
            new_name='descrição',
        ),
    ]
